const express = require('express');
const router = express.Router();
const postController = require('../app/api/controllers/posts');
router.get('/', postController.getAll);
router.post('/', postController.create);
router.get('/:post_id', postController.getById);
router.post('/:post_id/comment', postController.addNewComment);
router.post('/:post_id/like', postController.like);
router.post('/:post_id/unlike', postController.unlike);
module.exports = router;